name: Check for New Devices

on:
  schedule:
    - cron: '0 3 * * *'
    
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
    
env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

jobs:
  job:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Run Generator
      run: cd Generator; swift run
    - name: Check for changes
      run: |
        # true if changes detected
        isChanged=$(git diff-index --quiet HEAD -- || echo "true");
        echo "IS_CHANGED=$isChanged" >> $GITHUB_ENV
        if [[ $isChanged == "true" ]]; then
            echo "Changes detected"
        else
            echo "No changes detected"
        fi
    - name: "Ensure package still builds"
      if: ${{ env.IS_CHANGED == 'true' }}
      run: swift build --target Devices
    - name: "Create pull request"
      if: ${{ env.IS_CHANGED == 'true' }}
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update devices (autogenerated)"
        branch: "automated/update-devices"
        delete-branch: true
        title: "Update devices (autogenerated)"
        body: ""
        assignees: "ptrkstr"
